<?php

/**
 * @file
 * Primary module hooks for Books - Activity module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Set the title of the Book as Activity Title.
 *
 * @param \Drupal\node\Entity\Node $node
 *   The Activity being created.
 */
function books_activity_node_presave($node) {
  if ($node->bundle() === 'activity') {
    if ($book = $node->get('field_book')->entity) {
      $node->set('title', $book->label());
    }
  }
}

/**
 * Implements hook_theme().
 *
 * @phpstan-return array<string, array<string, mixed>>
 */
function books_activity_theme(): array {
  return [
    'activity_actions' => [
      'variables' => [
        'finish_url' => NULL,
        'abandon_url' => NULL,
      ],
    ],
    'book_start_action' => [
      'variables' => [
        'action' => NULL,
        'url' => NULL,
      ],
    ],
  ];
}
