<?php

/**
 * @file
 * Primary module hooks for Books - Catalog.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function books_catalog_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() === 'node' && $bundle === 'book') {
    if (isset($fields['field_isbn'])) {
      $fields['field_isbn']->addConstraint('UniqueField');
    }
  }
}
